name: Destroy Terraform Configuration

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment (e.g., production, staging)'
        required: true
        default: 'production'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.5.0'

      - name: Initialize Terraform
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        env:
          TF_VAR_environment: ${{ github.event.inputs.environment }}
