name: Destroy Terraform Configuration

on:
  workflow_dispatch: 

env:
  TF_CLOUD_ORGANIZATION: "organization_fhtechnikum"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"  
  TF_WORKSPACE: "learn-terraform-github-actions"  
  CONFIG_DIRECTORY: "./" 

jobs:
  terraform:
    runs-on: ubuntu-latest

    if: github.repository != 'hashicorp-education/learn-terraform-github-actions'

    name: "Terraform Destroy"
    
    permissions:
      contents: read

    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v3 

      - name: Upload Configuration
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.0.0 
        id: destroy-upload 
        with:
          workspace: ${{ env.TF_WORKSPACE }} 
          directory: ${{ env.CONFIG_DIRECTORY }} 

      - name: Terraform Destroy
        run: terraform destroy -auto-approve 
